# Generated by Django 5.2.4 on 2025-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namjestaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('kategorija', models.CharField(choices=[('DB', 'Dnevni boravak'), ('SS', 'Spavaća soba'), ('KU', 'Kuhinja'), ('DS', 'Dječija soba'), ('TR', 'Trpezarija'), ('HO', 'Hodnik')], max_length=2)),
                ('materijali', models.CharField(max_length=200)),
                ('količina_u_skladistu', models.PositiveIntegerField()),
                ('opis', models.TextField()),
                ('slika', models.ImageField(upload_to='namjestaj_slike/')),
                ('dodano_vrijeme', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
