# Generated by Django 5.2.4 on 2025-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namjestaj', '0002_alter_namjestaj_slika_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='namjestaj',
            name='izbrisano',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
