# Generated by Django 5.2.4 on 2025-08-17 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namjestaj', '0003_namjestaj_is_deleted_delete_upvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('procitana', models.BooleanField(default=False)),
                ('posiljalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poslate_poruke', to=settings.AUTH_USER_MODEL)),
                ('primalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primljene_poruke', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
